vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/%app.path.product_images%'
