easy_admin:
  entities:
    Categories:
      class: App\Entity\Categories
      form:
        fields:
          - {property: 'name'}
          - {property: 'parent'}
      list:
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}